title: This is my personal blog. Will write here something. Will keep you posted.
author: Oleksii Taran
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Here should be the description of this site, but it is not. Come here
  later.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
